# Generated by Django 3.2.24 on 2025-11-28 02:08

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(help_text='用户手机号，用于登录和验证', max_length=11, unique=True, verbose_name='手机号')),
                ('avatar', models.URLField(blank=True, help_text='用户头像图片链接', max_length=500, verbose_name='头像URL')),
                ('nickname', models.CharField(blank=True, help_text='用户自定义昵称', max_length=50, verbose_name='昵称')),
                ('birthday', models.DateField(blank=True, help_text='用户生日信息', null=True, verbose_name='生日')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('unknown', '未知')], default='unknown', help_text='用户性别信息', max_length=10, verbose_name='性别')),
                ('status', models.CharField(choices=[('active', '正常'), ('inactive', '禁用'), ('deleted', '已删除')], default='active', help_text='用户账号状态', max_length=20, verbose_name='用户状态')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='用户最后一次登录的IP地址', null=True, verbose_name='最后登录IP')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='用户注册时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='用户信息最后更新时间', verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
                'ordering': ['-create_time'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='用户的个人介绍', max_length=500, verbose_name='个人简介')),
                ('location', models.CharField(blank=True, help_text='用户所在城市或地区', max_length=100, verbose_name='所在地')),
                ('website', models.URLField(blank=True, help_text='用户的个人网站或博客链接', verbose_name='个人网站')),
                ('company', models.CharField(blank=True, help_text='用户所在公司', max_length=100, verbose_name='公司')),
                ('job_title', models.CharField(blank=True, help_text='用户的职位或头衔', max_length=100, verbose_name='职位')),
                ('preferences', models.JSONField(blank=True, default=dict, help_text='用户的个性化配置，JSON格式存储', verbose_name='用户偏好设置')),
                ('privacy_level', models.CharField(choices=[('public', '公开'), ('friends', '好友可见'), ('private', '私密')], default='public', help_text='用户信息的可见性设置', max_length=20, verbose_name='隐私级别')),
                ('email_verified', models.BooleanField(default=False, help_text='用户邮箱是否通过验证', verbose_name='邮箱已验证')),
                ('phone_verified', models.BooleanField(default=False, help_text='用户手机号是否通过验证', verbose_name='手机已验证')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '用户扩展资料',
                'verbose_name_plural': '用户扩展资料',
                'db_table': 'user_profiles',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='users_phone_af6883_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_usernam_baeb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status', 'create_time'], name='users_status_ae339c_idx'),
        ),
    ]
